# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_Workfile.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 768)
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TimeNow_Label = QtWidgets.QLabel(self.centralwidget)
        self.TimeNow_Label.setGeometry(QtCore.QRect(5, 32, 90, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.TimeNow_Label.setFont(font)
        self.TimeNow_Label.setMouseTracking(False)
        self.TimeNow_Label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TimeNow_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeNow_Label.setWordWrap(True)
        self.TimeNow_Label.setObjectName("TimeNow_Label")
        self.DateNow_Label = QtWidgets.QLabel(self.centralwidget)
        self.DateNow_Label.setGeometry(QtCore.QRect(5, 10, 90, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DateNow_Label.setFont(font)
        self.DateNow_Label.setMouseTracking(False)
        self.DateNow_Label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DateNow_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.DateNow_Label.setWordWrap(True)
        self.DateNow_Label.setObjectName("DateNow_Label")
        self.Index_Symbol_0 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Symbol_0.setGeometry(QtCore.QRect(100, 10, 40, 20))
        self.Index_Symbol_0.setObjectName("Index_Symbol_0")
        self.Index_Percentage_0 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Percentage_0.setGeometry(QtCore.QRect(100, 55, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Index_Percentage_0.setFont(font)
        self.Index_Percentage_0.setObjectName("Index_Percentage_0")
        self.Index_Price_0 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Price_0.setGeometry(QtCore.QRect(185, 10, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.Index_Price_0.setFont(font)
        self.Index_Price_0.setObjectName("Index_Price_0")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(95, 10, 3, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(230, 10, 3, 61))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Index_Symbol_1 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Symbol_1.setGeometry(QtCore.QRect(235, 10, 40, 20))
        self.Index_Symbol_1.setObjectName("Index_Symbol_1")
        self.Index_Percentage_1 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Percentage_1.setGeometry(QtCore.QRect(235, 55, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Index_Percentage_1.setFont(font)
        self.Index_Percentage_1.setObjectName("Index_Percentage_1")
        self.Index_Price_1 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Price_1.setGeometry(QtCore.QRect(320, 10, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.Index_Price_1.setFont(font)
        self.Index_Price_1.setObjectName("Index_Price_1")
        self.Index_Percentage_2 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Percentage_2.setGeometry(QtCore.QRect(370, 55, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Index_Percentage_2.setFont(font)
        self.Index_Percentage_2.setObjectName("Index_Percentage_2")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(365, 10, 3, 61))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.Index_Symbol_2 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Symbol_2.setGeometry(QtCore.QRect(370, 10, 40, 20))
        self.Index_Symbol_2.setObjectName("Index_Symbol_2")
        self.Index_Price_2 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Price_2.setGeometry(QtCore.QRect(450, 10, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.Index_Price_2.setFont(font)
        self.Index_Price_2.setObjectName("Index_Price_2")
        self.Index_Percentage_3 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Percentage_3.setGeometry(QtCore.QRect(505, 55, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Index_Percentage_3.setFont(font)
        self.Index_Percentage_3.setObjectName("Index_Percentage_3")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(500, 10, 3, 61))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.Index_Symbol_3 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Symbol_3.setGeometry(QtCore.QRect(505, 10, 40, 20))
        self.Index_Symbol_3.setObjectName("Index_Symbol_3")
        self.Index_Price_3 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Price_3.setGeometry(QtCore.QRect(590, 10, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.Index_Price_3.setFont(font)
        self.Index_Price_3.setObjectName("Index_Price_3")
        self.Index_Percentage_4 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Percentage_4.setGeometry(QtCore.QRect(640, 55, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Index_Percentage_4.setFont(font)
        self.Index_Percentage_4.setObjectName("Index_Percentage_4")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(635, 10, 3, 61))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.Index_Symbol_4 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Symbol_4.setGeometry(QtCore.QRect(640, 10, 40, 20))
        self.Index_Symbol_4.setObjectName("Index_Symbol_4")
        self.Index_Price_4 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Price_4.setGeometry(QtCore.QRect(725, 10, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.Index_Price_4.setFont(font)
        self.Index_Price_4.setObjectName("Index_Price_4")
        self.Index_Percentage_5 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Percentage_5.setGeometry(QtCore.QRect(775, 55, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Index_Percentage_5.setFont(font)
        self.Index_Percentage_5.setObjectName("Index_Percentage_5")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(770, 10, 3, 61))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.Index_Symbol_5 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Symbol_5.setGeometry(QtCore.QRect(775, 10, 40, 20))
        self.Index_Symbol_5.setObjectName("Index_Symbol_5")
        self.Index_Price_5 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Price_5.setGeometry(QtCore.QRect(860, 10, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.Index_Price_5.setFont(font)
        self.Index_Price_5.setObjectName("Index_Price_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 75, 1024, 5))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(905, 10, 3, 61))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.Index_Percentage_6 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Percentage_6.setGeometry(QtCore.QRect(910, 55, 50, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Index_Percentage_6.setFont(font)
        self.Index_Percentage_6.setObjectName("Index_Percentage_6")
        self.Index_Symbol_6 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Symbol_6.setGeometry(QtCore.QRect(910, 10, 40, 20))
        self.Index_Symbol_6.setObjectName("Index_Symbol_6")
        self.Index_Price_6 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Price_6.setGeometry(QtCore.QRect(980, 10, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.Index_Price_6.setFont(font)
        self.Index_Price_6.setObjectName("Index_Price_6")
        self.Index_Name_0 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Name_0.setGeometry(QtCore.QRect(100, 32, 130, 21))
        self.Index_Name_0.setObjectName("Index_Name_0")
        self.Index_Name_1 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Name_1.setGeometry(QtCore.QRect(235, 32, 130, 21))
        self.Index_Name_1.setObjectName("Index_Name_1")
        self.Index_Name_2 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Name_2.setGeometry(QtCore.QRect(370, 32, 130, 21))
        self.Index_Name_2.setObjectName("Index_Name_2")
        self.Index_Name_3 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Name_3.setGeometry(QtCore.QRect(505, 32, 130, 21))
        self.Index_Name_3.setObjectName("Index_Name_3")
        self.Index_Name_4 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Name_4.setGeometry(QtCore.QRect(640, 32, 130, 21))
        self.Index_Name_4.setObjectName("Index_Name_4")
        self.Index_Name_5 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Name_5.setGeometry(QtCore.QRect(775, 32, 130, 21))
        self.Index_Name_5.setObjectName("Index_Name_5")
        self.Index_Name_6 = QtWidgets.QLabel(self.centralwidget)
        self.Index_Name_6.setGeometry(QtCore.QRect(910, 32, 130, 21))
        self.Index_Name_6.setObjectName("Index_Name_6")
        self.Sector_Name_0 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Name_0.setGeometry(QtCore.QRect(14, 710, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sector_Name_0.setFont(font)
        self.Sector_Name_0.setObjectName("Sector_Name_0")
        self.Sector_Percentage_0 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Percentage_0.setGeometry(QtCore.QRect(154, 710, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sector_Percentage_0.setFont(font)
        self.Sector_Percentage_0.setObjectName("Sector_Percentage_0")
        self.Sector_Percentage_1 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Percentage_1.setGeometry(QtCore.QRect(154, 740, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sector_Percentage_1.setFont(font)
        self.Sector_Percentage_1.setObjectName("Sector_Percentage_1")
        self.Sector_Name_1 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Name_1.setGeometry(QtCore.QRect(14, 740, 39, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sector_Name_1.setFont(font)
        self.Sector_Name_1.setObjectName("Sector_Name_1")
        self.Sector_Percentage_2 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Percentage_2.setGeometry(QtCore.QRect(364, 710, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sector_Percentage_2.setFont(font)
        self.Sector_Percentage_2.setObjectName("Sector_Percentage_2")
        self.Sector_Name_2 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Name_2.setGeometry(QtCore.QRect(214, 710, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sector_Name_2.setFont(font)
        self.Sector_Name_2.setObjectName("Sector_Name_2")
        self.Sector_Percentage_3 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Percentage_3.setGeometry(QtCore.QRect(364, 740, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sector_Percentage_3.setFont(font)
        self.Sector_Percentage_3.setObjectName("Sector_Percentage_3")
        self.Sector_Name_3 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Name_3.setGeometry(QtCore.QRect(214, 740, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sector_Name_3.setFont(font)
        self.Sector_Name_3.setObjectName("Sector_Name_3")
        self.Sector_Percentage_4 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Percentage_4.setGeometry(QtCore.QRect(564, 710, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sector_Percentage_4.setFont(font)
        self.Sector_Percentage_4.setObjectName("Sector_Percentage_4")
        self.Sector_Name_4 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Name_4.setGeometry(QtCore.QRect(424, 710, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sector_Name_4.setFont(font)
        self.Sector_Name_4.setObjectName("Sector_Name_4")
        self.Sector_Percentage_5 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Percentage_5.setGeometry(QtCore.QRect(564, 740, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sector_Percentage_5.setFont(font)
        self.Sector_Percentage_5.setObjectName("Sector_Percentage_5")
        self.Sector_Name_5 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Name_5.setGeometry(QtCore.QRect(424, 740, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sector_Name_5.setFont(font)
        self.Sector_Name_5.setObjectName("Sector_Name_5")
        self.Sector_Percentage_6 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Percentage_6.setGeometry(QtCore.QRect(764, 710, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sector_Percentage_6.setFont(font)
        self.Sector_Percentage_6.setObjectName("Sector_Percentage_6")
        self.Sector_Name_6 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Name_6.setGeometry(QtCore.QRect(624, 710, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sector_Name_6.setFont(font)
        self.Sector_Name_6.setObjectName("Sector_Name_6")
        self.Sector_Percentage_7 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Percentage_7.setGeometry(QtCore.QRect(764, 740, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sector_Percentage_7.setFont(font)
        self.Sector_Percentage_7.setObjectName("Sector_Percentage_7")
        self.Sector_Name_7 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Name_7.setGeometry(QtCore.QRect(624, 740, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sector_Name_7.setFont(font)
        self.Sector_Name_7.setObjectName("Sector_Name_7")
        self.Sector_Name_9 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Name_9.setGeometry(QtCore.QRect(824, 740, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sector_Name_9.setFont(font)
        self.Sector_Name_9.setObjectName("Sector_Name_9")
        self.Sector_Percentage_9 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Percentage_9.setGeometry(QtCore.QRect(964, 740, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sector_Percentage_9.setFont(font)
        self.Sector_Percentage_9.setObjectName("Sector_Percentage_9")
        self.Sector_Name_8 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Name_8.setGeometry(QtCore.QRect(824, 710, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sector_Name_8.setFont(font)
        self.Sector_Name_8.setObjectName("Sector_Name_8")
        self.Sector_Percentage_8 = QtWidgets.QLabel(self.centralwidget)
        self.Sector_Percentage_8.setGeometry(QtCore.QRect(964, 710, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sector_Percentage_8.setFont(font)
        self.Sector_Percentage_8.setObjectName("Sector_Percentage_8")
        self.Sector_Performance_Title = QtWidgets.QComboBox(self.centralwidget)
        self.Sector_Performance_Title.setGeometry(QtCore.QRect(780, 680, 231, 30))
        self.Sector_Performance_Title.setObjectName("Sector_Performance_Title")
        self.Sector_Performance_Title.addItem("")
        self.Sector_Performance_Title.addItem("")
        self.Sector_Performance_Title.addItem("")
        self.Sector_Performance_Title.addItem("")
        self.Sector_Performance_Title.addItem("")
        self.Sector_Performance_Title.addItem("")
        self.Sector_Performance_Title.addItem("")
        self.Sector_Performance_Title.addItem("")
        self.Sector_Performance_Title.addItem("")
        self.Sector_Performance_Title.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 680, 1024, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(5, 55, 90, 15))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Search_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Search_Button.setGeometry(QtCore.QRect(105, 85, 25, 21))
        self.Search_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Search_Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Search_Button.setIcon(icon)
        self.Search_Button.setIconSize(QtCore.QSize(21, 21))
        self.Search_Button.setObjectName("Search_Button")
        self.Search_Bar = QtWidgets.QLineEdit(self.centralwidget)
        self.Search_Bar.setGeometry(QtCore.QRect(5, 85, 100, 21))
        self.Search_Bar.setObjectName("Search_Bar")
        self.Stock_Symbol = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Symbol.setGeometry(QtCore.QRect(140, 85, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Stock_Symbol.setFont(font)
        self.Stock_Symbol.setObjectName("Stock_Symbol")
        self.Stock_Description_Header = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Description_Header.setGeometry(QtCore.QRect(140, 140, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Stock_Description_Header.setFont(font)
        self.Stock_Description_Header.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Description_Header.setObjectName("Stock_Description_Header")
        self.Stock_Description = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Description.setGeometry(QtCore.QRect(140, 160, 371, 101))
        self.Stock_Description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Stock_Description.setWordWrap(True)
        self.Stock_Description.setObjectName("Stock_Description")
        self.Stock_Image = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Image.setGeometry(QtCore.QRect(5, 140, 100, 100))
        self.Stock_Image.setScaledContents(True)
        self.Stock_Image.setAlignment(QtCore.Qt.AlignCenter)
        self.Stock_Image.setObjectName("Stock_Image")
        self.Stock_Industry_Title = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Industry_Title.setGeometry(QtCore.QRect(530, 160, 100, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Stock_Industry_Title.setFont(font)
        self.Stock_Industry_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Industry_Title.setObjectName("Stock_Industry_Title")
        self.Stock_Exchange_Title = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Exchange_Title.setGeometry(QtCore.QRect(530, 180, 100, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Stock_Exchange_Title.setFont(font)
        self.Stock_Exchange_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Exchange_Title.setOpenExternalLinks(False)
        self.Stock_Exchange_Title.setObjectName("Stock_Exchange_Title")
        self.Stock_Industry = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Industry.setGeometry(QtCore.QRect(635, 160, 120, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_Industry.setFont(font)
        self.Stock_Industry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Industry.setObjectName("Stock_Industry")
        self.Stock_Exchange = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Exchange.setGeometry(QtCore.QRect(635, 180, 120, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_Exchange.setFont(font)
        self.Stock_Exchange.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Exchange.setObjectName("Stock_Exchange")
        self.Stock_Price = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Price.setGeometry(QtCore.QRect(215, 85, 50, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_Price.setFont(font)
        self.Stock_Price.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Price.setObjectName("Stock_Price")
        self.Stock_Percentage_Change = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Percentage_Change.setGeometry(QtCore.QRect(275, 85, 50, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_Percentage_Change.setFont(font)
        self.Stock_Percentage_Change.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Percentage_Change.setObjectName("Stock_Percentage_Change")
        self.Stock_Volume = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Volume.setGeometry(QtCore.QRect(670, 85, 125, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_Volume.setFont(font)
        self.Stock_Volume.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Volume.setObjectName("Stock_Volume")
        self.Stock_Line_1 = QtWidgets.QFrame(self.centralwidget)
        self.Stock_Line_1.setGeometry(QtCore.QRect(0, 105, 1024, 5))
        self.Stock_Line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.Stock_Line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Stock_Line_1.setObjectName("Stock_Line_1")
        self.Stock_Line_2 = QtWidgets.QFrame(self.centralwidget)
        self.Stock_Line_2.setGeometry(QtCore.QRect(0, 130, 1024, 5))
        self.Stock_Line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.Stock_Line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Stock_Line_2.setObjectName("Stock_Line_2")
        self.Stock_Name = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Name.setGeometry(QtCore.QRect(0, 110, 1024, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Stock_Name.setFont(font)
        self.Stock_Name.setStyleSheet("Background-color:rgb(128, 0, 128); Color:White")
        self.Stock_Name.setObjectName("Stock_Name")
        self.Stock_Market_Capitalization_Title = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Market_Capitalization_Title.setGeometry(QtCore.QRect(755, 160, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Stock_Market_Capitalization_Title.setFont(font)
        self.Stock_Market_Capitalization_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Market_Capitalization_Title.setObjectName("Stock_Market_Capitalization_Title")
        self.Stock_Beta = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Beta.setGeometry(QtCore.QRect(800, 85, 80, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_Beta.setFont(font)
        self.Stock_Beta.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Beta.setObjectName("Stock_Beta")
        self.Stock_Open = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Open.setGeometry(QtCore.QRect(340, 85, 100, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_Open.setFont(font)
        self.Stock_Open.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Open.setObjectName("Stock_Open")
        self.Stock_High = QtWidgets.QLabel(self.centralwidget)
        self.Stock_High.setGeometry(QtCore.QRect(440, 85, 100, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_High.setFont(font)
        self.Stock_High.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_High.setObjectName("Stock_High")
        self.Stock_Low = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Low.setGeometry(QtCore.QRect(540, 85, 100, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_Low.setFont(font)
        self.Stock_Low.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Low.setObjectName("Stock_Low")
        self.Stock_Earnings_Title = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Earnings_Title.setGeometry(QtCore.QRect(755, 180, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Stock_Earnings_Title.setFont(font)
        self.Stock_Earnings_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Earnings_Title.setOpenExternalLinks(False)
        self.Stock_Earnings_Title.setObjectName("Stock_Earnings_Title")
        self.Stock_Market_Capitalization = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Market_Capitalization.setGeometry(QtCore.QRect(840, 160, 120, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_Market_Capitalization.setFont(font)
        self.Stock_Market_Capitalization.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Market_Capitalization.setObjectName("Stock_Market_Capitalization")
        self.Stock_Earnings = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Earnings.setGeometry(QtCore.QRect(840, 180, 120, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_Earnings.setFont(font)
        self.Stock_Earnings.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Earnings.setObjectName("Stock_Earnings")
        self.Stock_AverageVolume_Title = QtWidgets.QLabel(self.centralwidget)
        self.Stock_AverageVolume_Title.setGeometry(QtCore.QRect(755, 200, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Stock_AverageVolume_Title.setFont(font)
        self.Stock_AverageVolume_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_AverageVolume_Title.setOpenExternalLinks(False)
        self.Stock_AverageVolume_Title.setObjectName("Stock_AverageVolume_Title")
        self.Stock_Average_Volume = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Average_Volume.setGeometry(QtCore.QRect(840, 200, 120, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_Average_Volume.setFont(font)
        self.Stock_Average_Volume.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Average_Volume.setObjectName("Stock_Average_Volume")
        self.Stock_View_Chart = QtWidgets.QPushButton(self.centralwidget)
        self.Stock_View_Chart.setGeometry(QtCore.QRect(5, 260, 100, 31))
        self.Stock_View_Chart.setStyleSheet("Background-Color:rgb(41, 91, 128);Color:White;Font:Bold")
        self.Stock_View_Chart.setObjectName("Stock_View_Chart")
        self.Stock_Avg_Price_200_Title = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Avg_Price_200_Title.setGeometry(QtCore.QRect(530, 200, 100, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Stock_Avg_Price_200_Title.setFont(font)
        self.Stock_Avg_Price_200_Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Stock_Avg_Price_200_Title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Avg_Price_200_Title.setOpenExternalLinks(False)
        self.Stock_Avg_Price_200_Title.setObjectName("Stock_Avg_Price_200_Title")
        self.Stock_Exchange_2 = QtWidgets.QLabel(self.centralwidget)
        self.Stock_Exchange_2.setGeometry(QtCore.QRect(635, 200, 120, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Stock_Exchange_2.setFont(font)
        self.Stock_Exchange_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Stock_Exchange_2.setObjectName("Stock_Exchange_2")
        self.label.raise_()
        self.TimeNow_Label.raise_()
        self.DateNow_Label.raise_()
        self.Index_Symbol_0.raise_()
        self.Index_Percentage_0.raise_()
        self.Index_Price_0.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.Index_Symbol_1.raise_()
        self.Index_Percentage_1.raise_()
        self.Index_Price_1.raise_()
        self.Index_Percentage_2.raise_()
        self.line_4.raise_()
        self.Index_Symbol_2.raise_()
        self.Index_Price_2.raise_()
        self.Index_Percentage_3.raise_()
        self.line_5.raise_()
        self.Index_Symbol_3.raise_()
        self.Index_Price_3.raise_()
        self.Index_Percentage_4.raise_()
        self.line_6.raise_()
        self.Index_Symbol_4.raise_()
        self.Index_Price_4.raise_()
        self.Index_Percentage_5.raise_()
        self.line_7.raise_()
        self.Index_Symbol_5.raise_()
        self.Index_Price_5.raise_()
        self.line.raise_()
        self.line_8.raise_()
        self.Index_Percentage_6.raise_()
        self.Index_Symbol_6.raise_()
        self.Index_Price_6.raise_()
        self.Index_Name_0.raise_()
        self.Index_Name_1.raise_()
        self.Index_Name_2.raise_()
        self.Index_Name_3.raise_()
        self.Index_Name_4.raise_()
        self.Index_Name_5.raise_()
        self.Index_Name_6.raise_()
        self.Sector_Name_0.raise_()
        self.Sector_Percentage_0.raise_()
        self.Sector_Percentage_1.raise_()
        self.Sector_Name_1.raise_()
        self.Sector_Percentage_2.raise_()
        self.Sector_Name_2.raise_()
        self.Sector_Percentage_3.raise_()
        self.Sector_Name_3.raise_()
        self.Sector_Percentage_4.raise_()
        self.Sector_Name_4.raise_()
        self.Sector_Percentage_5.raise_()
        self.Sector_Name_5.raise_()
        self.Sector_Percentage_6.raise_()
        self.Sector_Name_6.raise_()
        self.Sector_Percentage_7.raise_()
        self.Sector_Name_7.raise_()
        self.Sector_Name_9.raise_()
        self.Sector_Percentage_9.raise_()
        self.Sector_Name_8.raise_()
        self.Sector_Percentage_8.raise_()
        self.Sector_Performance_Title.raise_()
        self.label_2.raise_()
        self.Search_Button.raise_()
        self.Search_Bar.raise_()
        self.Stock_Symbol.raise_()
        self.Stock_Description_Header.raise_()
        self.Stock_Description.raise_()
        self.Stock_Image.raise_()
        self.Stock_Industry_Title.raise_()
        self.Stock_Exchange_Title.raise_()
        self.Stock_Industry.raise_()
        self.Stock_Exchange.raise_()
        self.Stock_Price.raise_()
        self.Stock_Percentage_Change.raise_()
        self.Stock_Volume.raise_()
        self.Stock_Line_1.raise_()
        self.Stock_Line_2.raise_()
        self.Stock_Name.raise_()
        self.Stock_Market_Capitalization_Title.raise_()
        self.Stock_Beta.raise_()
        self.Stock_Open.raise_()
        self.Stock_High.raise_()
        self.Stock_Low.raise_()
        self.Stock_Earnings_Title.raise_()
        self.Stock_Market_Capitalization.raise_()
        self.Stock_Earnings.raise_()
        self.Stock_AverageVolume_Title.raise_()
        self.Stock_Average_Volume.raise_()
        self.Stock_View_Chart.raise_()
        self.Stock_Avg_Price_200_Title.raise_()
        self.Stock_Exchange_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Will\'s Stock Screener"))
        self.TimeNow_Label.setText(_translate("MainWindow", "00:00:00"))
        self.DateNow_Label.setText(_translate("MainWindow", "Apr 14 2020"))
        self.Index_Symbol_0.setText(_translate("MainWindow", "SPY"))
        self.Index_Percentage_0.setText(_translate("MainWindow", "-0.00%"))
        self.Index_Price_0.setText(_translate("MainWindow", "100.00"))
        self.Index_Symbol_1.setText(_translate("MainWindow", "QQQ"))
        self.Index_Percentage_1.setText(_translate("MainWindow", "-0.00%"))
        self.Index_Price_1.setText(_translate("MainWindow", "100.00"))
        self.Index_Percentage_2.setText(_translate("MainWindow", "-0.00%"))
        self.Index_Symbol_2.setText(_translate("MainWindow", "IWM"))
        self.Index_Price_2.setText(_translate("MainWindow", "100.00"))
        self.Index_Percentage_3.setText(_translate("MainWindow", "-0.00%"))
        self.Index_Symbol_3.setText(_translate("MainWindow", "DIA"))
        self.Index_Price_3.setText(_translate("MainWindow", "100.00"))
        self.Index_Percentage_4.setText(_translate("MainWindow", "-0.00%"))
        self.Index_Symbol_4.setText(_translate("MainWindow", "^VIX"))
        self.Index_Price_4.setText(_translate("MainWindow", "100.00"))
        self.Index_Percentage_5.setText(_translate("MainWindow", "-0.00%"))
        self.Index_Symbol_5.setText(_translate("MainWindow", "GLD"))
        self.Index_Price_5.setText(_translate("MainWindow", "100.00"))
        self.Index_Percentage_6.setText(_translate("MainWindow", "-0.00%"))
        self.Index_Symbol_6.setText(_translate("MainWindow", "WTI"))
        self.Index_Price_6.setText(_translate("MainWindow", "100.00"))
        self.Index_Name_0.setText(_translate("MainWindow", "S&P 500 ETF Trust"))
        self.Index_Name_1.setText(_translate("MainWindow", "QQQ Trust"))
        self.Index_Name_2.setText(_translate("MainWindow", "Russell 2000 ETF"))
        self.Index_Name_3.setText(_translate("MainWindow", "Dow Jones Industrial"))
        self.Index_Name_4.setText(_translate("MainWindow", "Volatility Index"))
        self.Index_Name_5.setText(_translate("MainWindow", "Gold Shares"))
        self.Index_Name_6.setText(_translate("MainWindow", "Offshore, Inc."))
        self.Sector_Name_0.setText(_translate("MainWindow", "Consumer Discretionary"))
        self.Sector_Percentage_0.setText(_translate("MainWindow", "-0.00%"))
        self.Sector_Percentage_1.setText(_translate("MainWindow", "-0.00%"))
        self.Sector_Name_1.setText(_translate("MainWindow", "Energy"))
        self.Sector_Percentage_2.setText(_translate("MainWindow", "-0.00%"))
        self.Sector_Name_2.setText(_translate("MainWindow", "Communication Services"))
        self.Sector_Percentage_3.setText(_translate("MainWindow", "-0.00%"))
        self.Sector_Name_3.setText(_translate("MainWindow", "Information Technology"))
        self.Sector_Percentage_4.setText(_translate("MainWindow", "-0.00%"))
        self.Sector_Name_4.setText(_translate("MainWindow", "Consumer Staples"))
        self.Sector_Percentage_5.setText(_translate("MainWindow", "-0.00%"))
        self.Sector_Name_5.setText(_translate("MainWindow", "Health Care"))
        self.Sector_Percentage_6.setText(_translate("MainWindow", "-0.00%"))
        self.Sector_Name_6.setText(_translate("MainWindow", "Materials"))
        self.Sector_Percentage_7.setText(_translate("MainWindow", "-0.00%"))
        self.Sector_Name_7.setText(_translate("MainWindow", "Utilities"))
        self.Sector_Name_9.setText(_translate("MainWindow", "Financials"))
        self.Sector_Percentage_9.setText(_translate("MainWindow", "-0.00%"))
        self.Sector_Name_8.setText(_translate("MainWindow", "Industrials"))
        self.Sector_Percentage_8.setText(_translate("MainWindow", "-0.00%"))
        self.Sector_Performance_Title.setItemText(0, _translate("MainWindow", "Real-Time Performance"))
        self.Sector_Performance_Title.setItemText(1, _translate("MainWindow", "1 Day Performance"))
        self.Sector_Performance_Title.setItemText(2, _translate("MainWindow", "5 Day Performance"))
        self.Sector_Performance_Title.setItemText(3, _translate("MainWindow", "1 Month Performance"))
        self.Sector_Performance_Title.setItemText(4, _translate("MainWindow", "3 Month Performance"))
        self.Sector_Performance_Title.setItemText(5, _translate("MainWindow", "Year-to-Date (YTD) Performance"))
        self.Sector_Performance_Title.setItemText(6, _translate("MainWindow", "1 Year Performance"))
        self.Sector_Performance_Title.setItemText(7, _translate("MainWindow", "3 Year Performance"))
        self.Sector_Performance_Title.setItemText(8, _translate("MainWindow", "5 Year Performance"))
        self.Sector_Performance_Title.setItemText(9, _translate("MainWindow", "10 Year Performance"))
        self.label.setText(_translate("MainWindow", "Sector Performance"))
        self.label_2.setText(_translate("MainWindow", "Open"))
        self.Search_Bar.setPlaceholderText(_translate("MainWindow", "Tickers..."))
        self.Stock_Symbol.setText(_translate("MainWindow", "AAPL"))
        self.Stock_Description_Header.setText(_translate("MainWindow", "Description:"))
        self.Stock_Description.setText(_translate("MainWindow", "Apple Inc is designs, manufactures and markets mobile communication and media devices and personal computers, and sells a variety of related software, services, accessories, networking solutions and third-party digital content and applications."))
        self.Stock_Image.setText(_translate("MainWindow", "[img]"))
        self.Stock_Industry_Title.setText(_translate("MainWindow", "Industry:"))
        self.Stock_Exchange_Title.setText(_translate("MainWindow", "Exchange:"))
        self.Stock_Industry.setText(_translate("MainWindow", "Online Media"))
        self.Stock_Exchange.setText(_translate("MainWindow", "NASDAQ"))
        self.Stock_Price.setText(_translate("MainWindow", "69.00"))
        self.Stock_Percentage_Change.setText(_translate("MainWindow", "+0.15"))
        self.Stock_Volume.setText(_translate("MainWindow", "Vol: "))
        self.Stock_Name.setText(_translate("MainWindow", "AAPL"))
        self.Stock_Market_Capitalization_Title.setText(_translate("MainWindow", "Market Cap:"))
        self.Stock_Beta.setText(_translate("MainWindow", "Beta:"))
        self.Stock_Open.setText(_translate("MainWindow", "Open:"))
        self.Stock_High.setText(_translate("MainWindow", "H:"))
        self.Stock_Low.setText(_translate("MainWindow", "L:"))
        self.Stock_Earnings_Title.setText(_translate("MainWindow", "Earnings:"))
        self.Stock_Market_Capitalization.setText(_translate("MainWindow", "1.3 Billion"))
        self.Stock_Earnings.setText(_translate("MainWindow", "13-Apr-2020"))
        self.Stock_AverageVolume_Title.setText(_translate("MainWindow", "Avg Volume:"))
        self.Stock_Average_Volume.setText(_translate("MainWindow", "1234567890"))
        self.Stock_View_Chart.setText(_translate("MainWindow", "View Chart"))
        self.Stock_Avg_Price_200_Title.setText(_translate("MainWindow", "Price Avg 200:"))
        self.Stock_Exchange_2.setText(_translate("MainWindow", "243.22"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
